package com.xxx.domain.ticket;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.tn
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String tn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.title
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.queue_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer queueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_lock_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short ticketLockId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.service_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer serviceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.sla_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer slaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.responsible_user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer responsibleUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_priority_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short ticketPriorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.ticket_state_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short ticketStateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.customer_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.customer_user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String customerUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.timeout
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer timeout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.until_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer untilTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.escalation_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer escalationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.escalation_update_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer escalationUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.escalation_response_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer escalationResponseTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.escalation_solution_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer escalationSolutionTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.archive_flag
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short archiveFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_time_unix
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long createTimeUnix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer changeBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.id
     *
     * @return the value of ticket.id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.id
     *
     * @param id the value for ticket.id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.tn
     *
     * @return the value of ticket.tn
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getTn() {
        return tn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.tn
     *
     * @param tn the value for ticket.tn
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTn(String tn) {
        this.tn = tn == null ? null : tn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.title
     *
     * @return the value of ticket.title
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.title
     *
     * @param title the value for ticket.title
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.queue_id
     *
     * @return the value of ticket.queue_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.queue_id
     *
     * @param queueId the value for ticket.queue_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setQueueId(Integer queueId) {
        this.queueId = queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_lock_id
     *
     * @return the value of ticket.ticket_lock_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getTicketLockId() {
        return ticketLockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_lock_id
     *
     * @param ticketLockId the value for ticket.ticket_lock_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketLockId(Short ticketLockId) {
        this.ticketLockId = ticketLockId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.type_id
     *
     * @return the value of ticket.type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.type_id
     *
     * @param typeId the value for ticket.type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTypeId(Short typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.service_id
     *
     * @return the value of ticket.service_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getServiceId() {
        return serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.service_id
     *
     * @param serviceId the value for ticket.service_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setServiceId(Integer serviceId) {
        this.serviceId = serviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.sla_id
     *
     * @return the value of ticket.sla_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getSlaId() {
        return slaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.sla_id
     *
     * @param slaId the value for ticket.sla_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setSlaId(Integer slaId) {
        this.slaId = slaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.user_id
     *
     * @return the value of ticket.user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.user_id
     *
     * @param userId the value for ticket.user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.responsible_user_id
     *
     * @return the value of ticket.responsible_user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getResponsibleUserId() {
        return responsibleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.responsible_user_id
     *
     * @param responsibleUserId the value for ticket.responsible_user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setResponsibleUserId(Integer responsibleUserId) {
        this.responsibleUserId = responsibleUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_priority_id
     *
     * @return the value of ticket.ticket_priority_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getTicketPriorityId() {
        return ticketPriorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_priority_id
     *
     * @param ticketPriorityId the value for ticket.ticket_priority_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketPriorityId(Short ticketPriorityId) {
        this.ticketPriorityId = ticketPriorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.ticket_state_id
     *
     * @return the value of ticket.ticket_state_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getTicketStateId() {
        return ticketStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.ticket_state_id
     *
     * @param ticketStateId the value for ticket.ticket_state_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketStateId(Short ticketStateId) {
        this.ticketStateId = ticketStateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.customer_id
     *
     * @return the value of ticket.customer_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.customer_id
     *
     * @param customerId the value for ticket.customer_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.customer_user_id
     *
     * @return the value of ticket.customer_user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getCustomerUserId() {
        return customerUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.customer_user_id
     *
     * @param customerUserId the value for ticket.customer_user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCustomerUserId(String customerUserId) {
        this.customerUserId = customerUserId == null ? null : customerUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.timeout
     *
     * @return the value of ticket.timeout
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.timeout
     *
     * @param timeout the value for ticket.timeout
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.until_time
     *
     * @return the value of ticket.until_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getUntilTime() {
        return untilTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.until_time
     *
     * @param untilTime the value for ticket.until_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setUntilTime(Integer untilTime) {
        this.untilTime = untilTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.escalation_time
     *
     * @return the value of ticket.escalation_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getEscalationTime() {
        return escalationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.escalation_time
     *
     * @param escalationTime the value for ticket.escalation_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setEscalationTime(Integer escalationTime) {
        this.escalationTime = escalationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.escalation_update_time
     *
     * @return the value of ticket.escalation_update_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getEscalationUpdateTime() {
        return escalationUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.escalation_update_time
     *
     * @param escalationUpdateTime the value for ticket.escalation_update_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setEscalationUpdateTime(Integer escalationUpdateTime) {
        this.escalationUpdateTime = escalationUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.escalation_response_time
     *
     * @return the value of ticket.escalation_response_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getEscalationResponseTime() {
        return escalationResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.escalation_response_time
     *
     * @param escalationResponseTime the value for ticket.escalation_response_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setEscalationResponseTime(Integer escalationResponseTime) {
        this.escalationResponseTime = escalationResponseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.escalation_solution_time
     *
     * @return the value of ticket.escalation_solution_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getEscalationSolutionTime() {
        return escalationSolutionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.escalation_solution_time
     *
     * @param escalationSolutionTime the value for ticket.escalation_solution_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setEscalationSolutionTime(Integer escalationSolutionTime) {
        this.escalationSolutionTime = escalationSolutionTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.archive_flag
     *
     * @return the value of ticket.archive_flag
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getArchiveFlag() {
        return archiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.archive_flag
     *
     * @param archiveFlag the value for ticket.archive_flag
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setArchiveFlag(Short archiveFlag) {
        this.archiveFlag = archiveFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_time_unix
     *
     * @return the value of ticket.create_time_unix
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getCreateTimeUnix() {
        return createTimeUnix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_time_unix
     *
     * @param createTimeUnix the value for ticket.create_time_unix
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateTimeUnix(Long createTimeUnix) {
        this.createTimeUnix = createTimeUnix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_time
     *
     * @return the value of ticket.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_time
     *
     * @param createTime the value for ticket.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.create_by
     *
     * @return the value of ticket.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.create_by
     *
     * @param createBy the value for ticket.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.change_time
     *
     * @return the value of ticket.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.change_time
     *
     * @param changeTime the value for ticket.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.change_by
     *
     * @return the value of ticket.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getChangeBy() {
        return changeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.change_by
     *
     * @param changeBy the value for ticket.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setChangeBy(Integer changeBy) {
        this.changeBy = changeBy;
    }
}