package com.xxx.domain.ticket;

import java.util.Date;

public class TicketHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.name
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.history_type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short historyTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.article_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long articleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.queue_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer queueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.owner_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.priority_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short priorityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.state_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Short stateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_history.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer changeBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.id
     *
     * @return the value of ticket_history.id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.id
     *
     * @param id the value for ticket_history.id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.name
     *
     * @return the value of ticket_history.name
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.name
     *
     * @param name the value for ticket_history.name
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.history_type_id
     *
     * @return the value of ticket_history.history_type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getHistoryTypeId() {
        return historyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.history_type_id
     *
     * @param historyTypeId the value for ticket_history.history_type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setHistoryTypeId(Short historyTypeId) {
        this.historyTypeId = historyTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.ticket_id
     *
     * @return the value of ticket_history.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.ticket_id
     *
     * @param ticketId the value for ticket_history.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.article_id
     *
     * @return the value of ticket_history.article_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.article_id
     *
     * @param articleId the value for ticket_history.article_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setArticleId(Long articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.type_id
     *
     * @return the value of ticket_history.type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.type_id
     *
     * @param typeId the value for ticket_history.type_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTypeId(Short typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.queue_id
     *
     * @return the value of ticket_history.queue_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getQueueId() {
        return queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.queue_id
     *
     * @param queueId the value for ticket_history.queue_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setQueueId(Integer queueId) {
        this.queueId = queueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.owner_id
     *
     * @return the value of ticket_history.owner_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.owner_id
     *
     * @param ownerId the value for ticket_history.owner_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.priority_id
     *
     * @return the value of ticket_history.priority_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getPriorityId() {
        return priorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.priority_id
     *
     * @param priorityId the value for ticket_history.priority_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setPriorityId(Short priorityId) {
        this.priorityId = priorityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.state_id
     *
     * @return the value of ticket_history.state_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Short getStateId() {
        return stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.state_id
     *
     * @param stateId the value for ticket_history.state_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setStateId(Short stateId) {
        this.stateId = stateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.create_time
     *
     * @return the value of ticket_history.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.create_time
     *
     * @param createTime the value for ticket_history.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.create_by
     *
     * @return the value of ticket_history.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.create_by
     *
     * @param createBy the value for ticket_history.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.change_time
     *
     * @return the value of ticket_history.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.change_time
     *
     * @param changeTime the value for ticket_history.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_history.change_by
     *
     * @return the value of ticket_history.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getChangeBy() {
        return changeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_history.change_by
     *
     * @param changeBy the value for ticket_history.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setChangeBy(Integer changeBy) {
        this.changeBy = changeBy;
    }
}