package com.xxx.domain.ticket;

import java.util.Date;

public class TicketWatcher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_watcher.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_watcher.user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_watcher.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_watcher.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_watcher.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date changeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_watcher.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer changeBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watcher.ticket_id
     *
     * @return the value of ticket_watcher.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watcher.ticket_id
     *
     * @param ticketId the value for ticket_watcher.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watcher.user_id
     *
     * @return the value of ticket_watcher.user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watcher.user_id
     *
     * @param userId the value for ticket_watcher.user_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watcher.create_time
     *
     * @return the value of ticket_watcher.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watcher.create_time
     *
     * @param createTime the value for ticket_watcher.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watcher.create_by
     *
     * @return the value of ticket_watcher.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watcher.create_by
     *
     * @param createBy the value for ticket_watcher.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watcher.change_time
     *
     * @return the value of ticket_watcher.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watcher.change_time
     *
     * @param changeTime the value for ticket_watcher.change_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_watcher.change_by
     *
     * @return the value of ticket_watcher.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getChangeBy() {
        return changeBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_watcher.change_by
     *
     * @param changeBy the value for ticket_watcher.change_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setChangeBy(Integer changeBy) {
        this.changeBy = changeBy;
    }
}