package com.xxx.domain.ticket;

import java.util.Date;

public class TicketFlag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_flag.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Long ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_flag.ticket_key
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String ticketKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_flag.ticket_value
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private String ticketValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_flag.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_flag.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    private Integer createBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_flag.ticket_id
     *
     * @return the value of ticket_flag.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Long getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_flag.ticket_id
     *
     * @param ticketId the value for ticket_flag.ticket_id
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketId(Long ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_flag.ticket_key
     *
     * @return the value of ticket_flag.ticket_key
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getTicketKey() {
        return ticketKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_flag.ticket_key
     *
     * @param ticketKey the value for ticket_flag.ticket_key
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketKey(String ticketKey) {
        this.ticketKey = ticketKey == null ? null : ticketKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_flag.ticket_value
     *
     * @return the value of ticket_flag.ticket_value
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public String getTicketValue() {
        return ticketValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_flag.ticket_value
     *
     * @param ticketValue the value for ticket_flag.ticket_value
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setTicketValue(String ticketValue) {
        this.ticketValue = ticketValue == null ? null : ticketValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_flag.create_time
     *
     * @return the value of ticket_flag.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_flag.create_time
     *
     * @param createTime the value for ticket_flag.create_time
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_flag.create_by
     *
     * @return the value of ticket_flag.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public Integer getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_flag.create_by
     *
     * @param createBy the value for ticket_flag.create_by
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
}