package com.xxx.mapper.ticket;

import com.xxx.domain.ticket.TicketWatcher;

public interface TicketWatcherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_watcher
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insert(TicketWatcher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_watcher
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insertSelective(TicketWatcher record);
}