package com.xxx.mapper.ticket;

import com.xxx.domain.ticket.TicketHistory;

public interface TicketHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_history
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_history
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insert(TicketHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_history
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insertSelective(TicketHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_history
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    TicketHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_history
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKeySelective(TicketHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_history
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKey(TicketHistory record);
}