package com.xxx.mapper.ticket;

import com.xxx.domain.ticket.TicketType;

public interface TicketTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insert(TicketType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insertSelective(TicketType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    TicketType selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKeySelective(TicketType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_type
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKey(TicketType record);
}