package com.xxx.mapper.ticket;

import com.xxx.domain.ticket.TicketState;

public interface TicketStateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_state
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_state
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insert(TicketState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_state
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insertSelective(TicketState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_state
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    TicketState selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_state
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKeySelective(TicketState record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_state
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int updateByPrimaryKey(TicketState record);
}