package com.xxx.mapper.ticket;

import com.xxx.domain.ticket.TicketFlag;

public interface TicketFlagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_flag
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insert(TicketFlag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_flag
     *
     * @mbggenerated Wed Aug 09 14:40:40 CST 2017
     */
    int insertSelective(TicketFlag record);
}